### ISSUE TITLE
use with jekyll

### ISSUE THREAD

**Issue by koron** [sorapixels/eyecatch-bugs#1]
https://eyecatch.io/vim-jp/vim-jp.github.io/57a46421bd48f0291c1965c6/log

I want to try eyecatch.io with jekyll (github-pages).
But `bundle install` is failed because `ffi` module one of requirements of `jekyll` can't be compiled, lack of `-lgmp` (libgmp).

Do you have any plans to support this like case?

**Comment by xarsh** [comment]
Hi @koron,
Thank you very much for your feedback!

We are aware that the initial setup experience can be a little tedious, and are working very hard to improve it.
`libgmp` is now included as a default library and we checked that `ffi` module can be compiled without `apt-get` command.
We will add the relevant information to the documentation soon.
Please let us know if you run into any other issues.
